### ISSUE TITLE
Why the original repository no more exist? It was banned?

### ISSUE THREAD

**Issue by john-cj** [Wohlstand/Destroy-Windows-10-Spying#13]
It was banned? I ask it because I don't want the same fate for this one.

**Comment by Wohlstand** [comment]
The original repository was been removed together with the original author's account. The old build (before I had to fix it), contained a backdoor, added by "Renesans-biz" who was a new developers, unfortunately, they became jerks and gone away into the doom. A bit later, Nummer (original author), deleted all his accounts (Twitter, and GitHub too). He had no time and no desire to maintain the stuff, and he looked for a new developer who will pick up his work. I guess, he had to remove all his accounts to just disappear and stop any future disturbing of him by people.

**Comment by john-cj** [comment]
I really appreciated for your work on this project :+1: I'm currently on my old PC with Windows 7, and I was sure it will be necessary to switch on Mac (which is too expensive for me) or Linux (which doesn't have the software I need).

**Comment by Wohlstand** [comment]
I work with Linux (Linux Mint distro) on a desktop a long time (since the end of 2014), and I can tell that for Windows software that doesn't have the native analogs for Linux, may work through the Wine environment, otherwise, use a VirtualBox / VMWare Player to run a Windows VM inside of it to use the software that won't work on Wine properly, or need to debug a thing inside of real Windows OS environment. If your needed software requires a 3D, it works better in Wine than in VM. The big mess with .NET applications that are working better on VM.
